#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx_config
- name: insatltion of nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: take backup of files
  ansible.builtin.copy:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-available/default.backup
    remote_src: yes

- name: config change to run it on 90
  ansible.builtin.lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: '^(\s*listen\s+)(80)(\s*default_server:?)'
    line:   'listen 90 default_server;'
    backrefs: yes 

- name: Configure nginx to listen on IPv6 port 90
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: '^(\s*listen\s+)\[::\]:80(\s*default_server;?)'
    line: '    listen [::]:90 default_server;'
    backrefs: yes
  notify: restarted nginx
  changed_when: true